### ISSUE TITLE
Multiple Asset URIs

### ISSUE THREAD

**Issue by TimNFL** [hatharry/Emby.ServerUpdater#1]
I just installed the script and when I ran the task it was erroring out. I went and manually ran the task to debug and see where the problem was and I found this:

```
[DBG]: PS C:\WINDOWS\system32>> $this.assetUrl
https://github.com/MediaBrowser/Emby/releases/download/3.2.70.0/embyserver-win-x64-3.2.70.0.7z
https://github.com/MediaBrowser/Emby/releases/download/3.2.70.0/embyserver-windows-x64-3.2.70.0.7z
```

I manually modified line 68 to read
`Invoke-WebRequest $this.assetUrl[0] -OutFile "$($this.location)\updates\MBserver.zip" -UseBasicParsing`

this resolved the issue but I am not sure this is truly the proper way to handle the situation. I figured I'd let you know

**Comment by TimNFL** [comment]
Will there be an update that handles multiple URIs?



________________________________

**Comment by hatharry** [comment]
fixed in the latest update
