### ISSUE TITLE
Beta Updates

### ISSUE THREAD

**Issue by TimNFL** [hatharry/Emby.ServerUpdater#2]
I am having 2 issues with the script.

1. Since I have an Emby server on the Beta Channel, when I change line 36 to equal $true, when I update the script it clears out this customization and I have to remember to update that as well. SInce I have a schedule task that updates the script, these changes are lost each time the script is updated
2. Line 62 is not comparing versions correctly. Currently $this.release.tag_name = 4.1.0.10 and $this.localVersion = 4.1.0.9 so the comparison of $this.release.tag_name -gt $this.localversion is returning false instead of true. Since $this.localversion is already of the type [system.version], If I cast $this.release.tag_name to the same type it works as expected. my Modified line looks like this. 
`if ([version]$this.release.tag_name -gt $this.localVersion) {`

**Comment by hatharry** [comment]
Both after fixed in latest commit
