### ISSUE TITLE
Maybe I do not know how to run the script. The README wasn't all that descriptive..

### ISSUE THREAD

**Issue by mcfalld** [hatharry/Emby.ServerUpdater#3]
Its possible I just dont know what I am doing, but I get:

At C:\Users\mcfal\Downloads\Emby.ServerUpdater-master\Emby.ServerUpdater-master\EmbyServiceUpdater.ps1:2 char:13
+ #requires â€“runasadministrator
+             ~~~~~~~~~~~~~~~~~~~
The string is missing the terminator: ".
At C:\Users\mcfal\Downloads\Emby.ServerUpdater-master\Emby.ServerUpdater-master\EmbyServiceUpdater.ps1:2 char:11
+ #requires â€“runasadministrator
+           ~~~~~~~~~~~~~~~~~~~~~
Cannot process the #requires statement because it is not in the correct format.
The #requires statement must be in one of the following formats:
 "#requires -shellid <shellID>"
 "#requires -version <major.minor>"
 "#requires -psedition <edition>"
 "#requires -pssnapin <psSnapInName> [-version <major.minor>]"
 "#requires -modules <ModuleSpecification>"
 "#requires -runasadministrator"
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : TerminatorExpectedAtEndOfString

![image](https://user-images.githubusercontent.com/32588824/54469878-8b436280-476c-11e9-994c-ac4f1f7a97aa.png)

**Comment by hatharry** [comment]
fixed in latest commit
