### ISSUE TITLE
error when running

### ISSUE THREAD

**Issue by mcfalld** [hatharry/Emby.ServerUpdater#5]
.\EmbyServiceUpdater.ps1 -ApiKey "****" -ServerUrl "http://192.168.111.11:8096" -update
![Untitled](https://user-images.githubusercontent.com/32588824/57491956-85f22800-7284-11e9-9681-72daae24ec41.png)

This is what i get when i run the command (if you can see the picture). Am I running it wrong? I don't think the ReadMe is very clear sorry for being a bother about it. I'm not sure what [-InstallTask] and the other options actually mean. Please help me.

**Comment by hatharry** [comment]
copy [this](https://raw.githubusercontent.com/hatharry/Emby.ServerUpdater/master/EmbyServiceUpdater.ps1) into EmbyServiceUpdater.ps1

then run:

.\EmbyServiceUpdater.ps1 -ApiKey "YOUR_API_KEY" -ServerUrl "http://YOUR_SERVER_URL:PORT" -InstallTask

That is all!

**Comment by mcfalld** [comment]
okay not sure why i struggled so much with that. How can I get back to the stable version?

**Comment by hatharry** [comment]
Replace your system folder with [this](https://github.com/MediaBrowser/Emby.Releases/releases/download/4.1.1.0/embyserver-win-x64-4.1.1.0.7z)

**Comment by mcfalld** [comment]
You are a gentleman and a scholar. Thank you very much.
