### ISSUE TITLE
Script will crash if multiple instances of emby process are present

### ISSUE THREAD

**Issue by ocalvo** [hatharry/Emby.ServerUpdater#6]
[The location property](https://github.com/hatharry/Emby.ServerUpdater/blob/master/EmbyServiceUpdater.ps1#L39) will return an array of strings instead of a single string if multiple processes for Emby are present in the system.

Suggestion to change to:
```
 $embyProc = (Get-Process embyserver)
 if ($embyProc.Length -ne 1)
 {
    Write-Error "Multiple instances of emby running detected"
 }
 $this.location = (Get-Item $embyProc.Path).Directory.Parent.FullName
```

**Comment by hatharry** [comment]
051d017
